name: rtc-example
base: core18
version: '1.2.2-r0.3'
summary: ConsoleIn/ConsoleOut RTC
description: |
  OpenRTM-aist

confinement: 'strict'
grade: devel

architectures:
  - amd64

layout:
  /usr:
    bind: $SNAP/usr

plugs:
  openrtm0-1804:
    interface: content
    content: openrtm0-1804
    target: $SNAP/extra-libs
  
apps:
  ConsoleInComp:
    command: usr/share/openrtm-1.2/components/c++/examples/ConsoleInComp
    plugs:
      - network
      - network-bind
  
  ConsoleOutComp:
    command: usr/share/openrtm-1.2/components/c++/examples/ConsoleOutComp
    plugs:
      - network
      - network-bind

parts:
  openrtm:
    source: https://github.com/openrtm/OpenRTM-aist.git
    source-tag: v1.2.2
    plugin: autotools
    configflags:
      - --without-doxygen
      - --with-omniorb=${SNAPCRAFT_STAGE}/usr
      - --prefix=/usr
      - --disable-fluentd
      - --disable-test
      - CXXFLAGS=-Wno-deprecated -Wno-Wunused-result -Wno-sign-compare -Wno-unused-variable

    build-packages:
      - libomniorb4-dev
      - omniidl
      - omniorb-nameserver
      - python3-yaml
      - gcc
      - g++
      - make
      - cmake
      - doxygen
      - graphviz
      - nkf
      - pkg-config
      - libtool-bin
      - uuid-dev
      - libboost-filesystem-dev

    stage-packages:
      - libboost-filesystem1.65.1
      - libboost-system1.65.1
