name: rtshell
base: core18
version: '1.2.2-r0.5'
summary: OpenRTM RTShell
description: |
  OpenRTM-aist

confinement: 'strict'
grade: devel

architectures:
  - amd64

slots:
    openrtm0-1804:
       interface: content
       content: openrtm0-1804
       read:
        - $SNAP/usr
apps:
  rtshell:
    command: bin/bash
    plugs:
      - network
      - network-bind

parts:
  add-repo:
    plugin: nil
    override-pull: |
      sed -i s/archive.ubuntu.com/jp.archive.ubuntu.com/ /etc/apt/sources.list
      apt update
      apt -yy upgrade
      apt -yy install wget gnupg
      wget -O- --secure-protocol=TLSv1_2 --no-check-certificate https://openrtm.org/pub/openrtm.key | apt-key add -
      echo "deb http://openrtm.org/pub/Linux/ubuntu bionic main" >  /etc/apt/sources.list.d/openrtm.list
      apt update

  rtshell:
    plugin: python
    after: ['add-repo']
    python-packages:
      - rtshell-aist

    build-packages:
      - openrtm-aist-python3
      - python3-omniorb
      - omniorb
      - omniidl-python3
      - omniidl

    override-stage: |
      snapcraftctl stage
      rtshell_post_install -n -p $SNAPCRAFT_STAGE/usr/bin
      
    stage-packages:
      - openrtm-aist-python3
      - python3-omniorb
      - bash