name: rtm
base: core18
version: '0.1'
summary: OpenRTM nameserver
description: |
  OpenRTM-aist

confinement: 'strict'
grade: devel
architectures:
  - amd64

apps:
  naming:
    command: omniNames -start -always -datadir $SNAP_USER_DATA
    daemon: simple
    plugs:
      - network
      - network-bind
  
  ConsoleInComp:
    command: share/openrtm-2.0/components/c++/examples/ConsoleInComp
    plugs:
      - network
      - network-bind
  
  ConsoleOutComp:
    command: share/openrtm-2.0/components/c++/examples/ConsoleOutComp
    plugs:
      - network
      - network-bind
  
build-packages:
    - autoconf
    - libtool
    - libtool-bin
    - bc
    - flex
    - bison
    - iputils-ping
    - net-tools
    - python3-yaml
    - gcc
    - g++
    - make
    - cmake
    - doxygen
    - graphviz
    - nkf
    - subversion
    - git
    - uuid-dev
    - libboost-filesystem-dev
    - build-essential
    - debhelper
    - devscripts
    - libomniorb4-dev
    - omniidl
    - omniorb-nameserver

parts:
    fluent-bit:
        source: https://github.com/fluent/fluent-bit.git
        plugin: cmake
        configflags:
            - -DFLB_DEBUG=Off
            - -DFLB_TRACE=Off
            - -DFLB_JEMALLOC=On
            - -DFLB_TLS=On
            - -DFLB_SHARED_LIB=On
            - -DFLB_EXAMPLES=Off
            - -DFLB_HTTP_SERVER=On
            - -DFLB_IN_SYSTEMD=On
            - -DFLB_OUT_KAFKA=On
            - -DCMAKE_BUILD_TYPE=Release

    openrtm:
        source: https://github.com/openrtm/OpenRTM-aist.git
        plugin: cmake
        configflags:
          - -DSSL_ENABLE=ON
          - -DOBSERVER_ENABLE=OFF
          - -DFLUENTBIT_ENABLE=OFF
          - -DFLUENTBIT_ROOT=usr/local/include
          - -DROS_ENABLE=OFF
          - -DFASTRTPS_ENABLE=OFF
          - -DROS2_ENABLE=OFF
          - -DCMAKE_BUILD_TYPE=Release
        stage-packages:
          - omniorb-nameserver
          - libboost-filesystem1.65.1
          - libboost-system1.65.1
          - libomniorb4-2
          - libomnithread4
        after: [fluent-bit]
