name: openrtm
base: core18
version: '1.2.2-r0.2'
summary: OpenRTM nameserver
description: |
  OpenRTM-aist

confinement: 'strict'
grade: devel

architectures:
  - amd64

apps:
  naming:
    command: omniNames -start -always -datadir $SNAP_USER_DATA
    daemon: simple
    plugs:
      - network
      - network-bind
  
  ConsoleInComp:
    command: share/openrtm-1.2/components/c++/examples/ConsoleInComp
    plugs:
      - network
      - network-bind
  
  ConsoleOutComp:
    command: share/openrtm-1.2/components/c++/examples/ConsoleOutComp
    plugs:
      - network
      - network-bind

parts:
  omniorb:
    plugin: make
    source: https://downloads.sourceforge.net/project/omniorb/omniORB/omniORB-4.2.4/omniORB-4.2.4.tar.bz2
    build-environment:
      - DESTDIR: ${SNAPCRAFT_PART_INSTALL}
    override-build: |
      ${SNAPCRAFT_PART_SRC}/configure --prefix=/usr --with-openssl=/usr
      snapcraftctl build
    make-parameters: 
      - "-j${SNAPCRAFT_PARALLEL_BUILD_COUNT}"
    build-packages:
      - g++
      - pkg-config
      - libssl-dev
      - python3-dev
    stage:
      - usr/*
      - -usr/**/__pycache__/*.pyc

  omniorbpy:
    plugin: make
    source: https://downloads.sourceforge.net/project/omniorb/omniORBpy/omniORBpy-4.2.4/omniORBpy-4.2.4.tar.bz2
    build-environment:
      - DESTDIR: ${SNAPCRAFT_PART_INSTALL}
    override-build: |
      ${SNAPCRAFT_PART_SRC}/configure --prefix=/usr --with-omniorb=${SNAPCRAFT_STAGE}/usr
      snapcraftctl build
#     
    make-parameters: 
      - "-j${SNAPCRAFT_PARALLEL_BUILD_COUNT}"
    after: [omniorb]

  openrtm:
    source: https://github.com/openrtm/OpenRTM-aist.git
    source-tag: v1.2.2
    plugin: autotools
    configflags:
      - --without-doxygen
      - --with-omniorb=${SNAPCRAFT_STAGE}/usr
      - --prefix=/usr
      - --disable-fluentd
      - --disable-test
      - CXXFLAGS=-Wno-deprecated -Wno-Wunused-result -Wno-sign-compare -Wno-unused-variable
    after: [omniorb]
    build-packages:
      - pkg-config
      - libtool-bin
      - uuid-dev
      - libboost-filesystem-dev
    stage-packages:
      - libboost-filesystem1.65.1
      - libboost-system1.65.1
#      - autoconf
#      - autotools-dev
#      - libtool
#      - libtool-bin
#      - bc
#      - flex
#      - bison
#      - iputils-ping
#      - python3-yaml
#      - gcc
#      - g++
#      - cmake
#      - doxygen
#      - graphviz
#      - nkf
#      - git
#      - uuid-dev
#      - build-essential
#      - debhelper
#      - devscripts
#     stage-packages:
#       - omniorb-nameserver
#       - libomniorb4-dev
#       - omniidl
#       - libboost-filesystem-dev
#       - libboost-system-dev
#       - libomniorb4-2
#       - libomnithread4
