name: rtm
base: core18
version: '0.1'
summary: OpenRTM nameserver
description: |
  OpenRTM-aist

confinement: 'strict'
grade: devel
architectures:
  - amd64

apps:
  naming:
    command: omniNames -start -always -datadir $SNAP_USER_DATA
    daemon: simple
    plugs:
      - network
      - network-bind
  
  ConsoleInComp:
    command: share/openrtm-1.2/components/c++/examples/ConsoleInComp
    plugs:
      - network
      - network-bind
  
  ConsoleOutComp:
    command: share/openrtm-1.2/components/c++/examples/ConsoleOutComp
    plugs:
      - network
      - network-bind

parts:
  openrtm:
    source: https://github.com/openrtm/OpenRTM-aist.git
    source-tag: v1.2.2
    plugin: autotools
    build-packages:
      - autoconf
      - autotools-dev
      - libtool
      - libtool-bin
      - bc
      - flex
      - bison
      - iputils-ping
      - python3-yaml
      - gcc
      - g++
      - cmake
      - doxygen
      - graphviz
      - nkf
      - git
      - uuid-dev
      - libboost-filesystem-dev
      - build-essential
      - debhelper
      - devscripts
      - omniidl
      - omniidl-python
    stage-packages:
      - omniorb-nameserver
      - libomniorb4-dev
      - omniidl
      - libboost-filesystem-dev
      - libboost-system-dev
      - libomniorb4-2
      - libomnithread4
